import React from 'react';

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
  } as React.CSSProperties,
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as React.CSSProperties,
  title: {
    fontSize: '2.25rem',
    marginBottom: '0.25rem',
    fontWeight: 700,
  } as React.CSSProperties,
  subtitle: {
    color: 'var(--text-secondary)',
    fontSize: '0.95rem',
  } as React.CSSProperties,
  adminLayout: {
    display: 'grid',
    gridTemplateColumns: '1.5fr 1fr',
    gap: '2rem',
  } as React.CSSProperties,
  panelCard: {
    borderRadius: '16px',
    border: '1px solid var(--border-color)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  } as React.CSSProperties,
  cardHeader: {
    padding: '1.25rem 1.5rem',
    borderBottom: '1px solid var(--border-color)',
    backgroundColor: 'rgba(0,0,0,0.15)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  } as React.CSSProperties,
  cardTitle: {
    fontSize: '1.1rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: 0,
  } as React.CSSProperties,
  cardBody: {
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  usersTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '0.85rem',
    textAlign: 'left',
  } as React.CSSProperties,
  tableHeader: {
    borderBottom: '2px solid var(--border-color)',
    color: 'var(--text-secondary)',
  } as React.CSSProperties,
  tableRow: {
    borderBottom: '1px solid var(--border-color)',
    transition: 'background var(--transition-fast)',
  } as React.CSSProperties,
  avatar: {
    width: '32px',
    height: '32px',
    backgroundColor: 'var(--primary)',
    color: 'white',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: '0.9rem',
  } as React.CSSProperties,
  userCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  } as React.CSSProperties,
  roleBadge: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: 'var(--primary)',
    backgroundColor: 'rgba(249, 115, 22, 0.05)',
    border: '1px solid rgba(249, 115, 22, 0.1)',
    padding: '0.2rem 0.5rem',
    borderRadius: '6px',
    textTransform: 'uppercase',
    display: 'inline-block',
  } as React.CSSProperties,
  actionBtn: {
    background: 'none',
    border: '1px solid var(--border-color)',
    color: 'var(--color-error)',
    width: '28px',
    height: '28px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
};
