import React from 'react';

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
  } as React.CSSProperties,
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as React.CSSProperties,
  title: {
    fontSize: '2.25rem',
    marginBottom: '0.25rem',
    fontWeight: 700,
  } as React.CSSProperties,
  subtitle: {
    color: 'var(--text-secondary)',
    fontSize: '0.95rem',
  } as React.CSSProperties,
  categoryFilters: {
    display: 'flex',
    gap: '0.5rem',
    overflowX: 'auto',
    paddingBottom: '0.5rem',
  } as React.CSSProperties,
  categoryTab: {
    padding: '0.6rem 1.25rem',
    borderRadius: '10px',
    border: '1px solid var(--border-color)',
    fontWeight: 600,
    fontSize: '0.85rem',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
  menuTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '0.9rem',
    minWidth: '600px',
  } as React.CSSProperties,
  menuTableHeader: {
    borderBottom: '2px solid var(--border-color)',
    color: 'var(--text-secondary)',
    textAlign: 'left',
  } as React.CSSProperties,
  menuTableRow: {
    borderBottom: '1px solid var(--border-color)',
    transition: 'background var(--transition-fast)',
  } as React.CSSProperties,
  menuTableDishCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    maxWidth: '400px',
  } as React.CSSProperties,
  dishColorIcon: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 'bold',
  } as React.CSSProperties,
  dishTableDesc: {
    display: 'block',
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
    fontWeight: 'normal',
    marginTop: '0.15rem',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  catTableBadge: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    padding: '0.25rem 0.5rem',
    borderRadius: '6px',
    border: '1px solid var(--border-color)',
    textTransform: 'uppercase',
  } as React.CSSProperties,
  tableActionsWrapper: {
    display: 'flex',
    gap: '0.5rem',
    justifyContent: 'flex-end',
  } as React.CSSProperties,
  tableActionBtn: {
    background: 'none',
    border: '1px solid var(--border-color)',
    color: 'var(--text-secondary)',
    width: '28px',
    height: '28px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
  // Dialog/Modal styles
  detailModal: {
    maxWidth: '500px',
    width: '100%',
    margin: '2rem auto',
    padding: '0',
    backgroundColor: 'rgba(22, 26, 36, 0.95)',
    borderRadius: '20px',
    border: '1px solid var(--border-color)',
    boxShadow: 'var(--shadow-xl)',
    display: 'flex',
    flexDirection: 'column',
    animation: 'scaleIn 0.2s ease-out',
  } as React.CSSProperties,
  detailModalHeader: {
    padding: '1.25rem 1.5rem',
    borderBottom: '1px solid var(--border-color)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as React.CSSProperties,
  detailModalBody: {
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  modalButtons: {
    display: 'flex',
    gap: '1rem',
    marginTop: '1rem',
  } as React.CSSProperties,
};
