import React from 'react';

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
  } as React.CSSProperties,
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as React.CSSProperties,
  headerLeft: {
    display: 'flex',
    flexDirection: 'column',
  } as React.CSSProperties,
  headerRight: {
    display: 'flex',
    gap: '0.75rem',
    alignItems: 'center',
  } as React.CSSProperties,
  title: {
    fontSize: '2.25rem',
    marginBottom: '0.25rem',
    fontWeight: 700,
  } as React.CSSProperties,
  subtitle: {
    color: 'var(--text-secondary)',
    fontSize: '0.95rem',
  } as React.CSSProperties,
  newOrderBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  } as React.CSSProperties,
  cierreCajaBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    color: 'var(--color-ready)',
    border: '1px solid var(--color-ready-border)',
    padding: '0.6rem 1.25rem',
    borderRadius: '12px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '0.95rem',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
  filtersWrapper: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid var(--border-color)',
    paddingBottom: '0.5rem',
  } as React.CSSProperties,
  tabsContainer: {
    display: 'flex',
    gap: '0.25rem',
  } as React.CSSProperties,
  filterTab: {
    border: '1px solid transparent',
    padding: '0.5rem 1rem',
    borderRadius: '8px',
    fontWeight: 600,
    fontSize: '0.85rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
  tabCount: {
    fontSize: '0.7rem',
    padding: '0.1rem 0.4rem',
    borderRadius: '6px',
    fontWeight: 700,
  } as React.CSSProperties,
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '1.5rem',
  } as React.CSSProperties,
  cardHover: {
    cursor: 'pointer',
    position: 'relative',
  } as React.CSSProperties,
  statusRibbon: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '4px',
    borderTopLeftRadius: '16px',
    borderTopRightRadius: '16px',
  } as React.CSSProperties,
  cardHeaderTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as React.CSSProperties,
  ticketId: {
    fontSize: '0.85rem',
    fontWeight: 800,
    color: 'var(--text-primary)',
  } as React.CSSProperties,
  timeTag: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
    fontWeight: 600,
  } as React.CSSProperties,
  tableTag: {
    fontSize: '1.25rem',
    fontWeight: 800,
    color: 'var(--text-primary)',
    marginTop: '0.5rem',
  } as React.CSSProperties,
  clientTag: {
    fontSize: '0.8rem',
    color: 'var(--text-secondary)',
    marginTop: '0.2rem',
    fontWeight: 500,
  } as React.CSSProperties,
  moreItems: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
    fontStyle: 'italic',
    padding: '0.25rem 0',
  } as React.CSSProperties,
  cardStatusFooter: {
    display: 'flex',
    justifyContent: 'flex-start',
    marginTop: '1rem',
  } as React.CSSProperties,
  emptyContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4rem 2rem',
    textAlign: 'center',
    borderRadius: '24px',
    border: '1px solid var(--border-color)',
    gap: '0.5rem',
  } as React.CSSProperties,
  // Modal detail
  detailModal: {
    maxWidth: '550px',
    width: '90vw',
    backgroundColor: 'rgba(22, 26, 36, 0.98)',
    borderRadius: '24px',
    border: '1px solid var(--border-color)',
    boxShadow: 'var(--shadow-2xl)',
    display: 'flex',
    flexDirection: 'column',
    animation: 'scaleIn 0.2s ease-out',
    padding: 0,
    overflow: 'hidden',
  } as React.CSSProperties,
  detailModalHeader: {
    padding: '1.25rem 1.5rem',
    borderBottom: '1px solid var(--border-color)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.1)',
  } as React.CSSProperties,
  detailModalBody: {
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
    maxHeight: 'calc(80vh - 70px)',
    overflowY: 'auto',
  } as React.CSSProperties,
  detailsTicketBg: {
    backgroundColor: 'white',
    color: '#1e293b',
    padding: '1.5rem',
    borderRadius: '16px',
    boxShadow: 'inset 0 0 10px rgba(0,0,0,0.05)',
    position: 'relative',
    fontFamily: 'Courier New, Courier, monospace',
  } as React.CSSProperties,
  ticketDotLine: {
    height: '4px',
    backgroundImage: 'radial-gradient(circle, #cbd5e1 2px, transparent 2.5px)',
    backgroundSize: '8px 4px',
    backgroundRepeat: 'repeat-x',
    marginBottom: '1rem',
  } as React.CSSProperties,
  ticketMetaRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.85rem',
    marginBottom: '0.75rem',
    color: '#334155',
  } as React.CSSProperties,
  ticketSeparator: {
    borderBottom: '1px dashed #cbd5e1',
    margin: '1rem 0',
  } as React.CSSProperties,
  ticketTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '0.85rem',
    color: '#1e293b',
  } as React.CSSProperties,
  ticketTableHeader: {
    borderBottom: '1px solid #e2e8f0',
    fontSize: '0.75rem',
    color: '#64748b',
  } as React.CSSProperties,
  ticketTableRow: {
    borderBottom: '1px solid #f1f5f9',
  } as React.CSSProperties,
  ticketNotesBox: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    padding: '0.75rem',
    borderRadius: '8px',
    fontSize: '0.8rem',
    color: '#475569',
    marginTop: '1rem',
  } as React.CSSProperties,
  ticketTotalBox: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '1.5rem',
    fontSize: '1rem',
    fontWeight: 'bold',
    color: '#0f172a',
  } as React.CSSProperties,
  ticketTotalVal: {
    fontSize: '1.35rem',
  } as React.CSSProperties,
  actionsPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  actionStatusGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  } as React.CSSProperties,
  actionButtonsRow: {
    display: 'flex',
    gap: '0.75rem',
  } as React.CSSProperties,
  deleteZone: {
    borderTop: '1px solid var(--border-color)',
    paddingTop: '1rem',
    marginTop: '0.5rem',
  } as React.CSSProperties,
  confirmDeleteBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    padding: '1rem',
    borderRadius: '12px',
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    border: '1px solid var(--color-error-border)',
  } as React.CSSProperties,
  confirmButtons: {
    display: 'flex',
    gap: '0.75rem',
  } as React.CSSProperties,
};
