import React from 'react';

export const styles = {
  modalContent: {
    maxWidth: '1100px',
    width: '95vw',
    height: '90vh',
    display: 'flex',
    flexDirection: 'column',
    padding: 0,
    backgroundColor: 'rgba(22, 26, 36, 0.98)',
    borderRadius: '24px',
    border: '1px solid var(--border-color)',
    boxShadow: 'var(--shadow-2xl)',
    animation: 'scaleIn 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
    overflow: 'hidden',
  } as React.CSSProperties,
  modalHeader: {
    padding: '1.25rem 1.5rem',
    borderBottom: '1px solid var(--border-color)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '70px',
    backgroundColor: 'rgba(0,0,0,0.1)',
  } as React.CSSProperties,
  headerTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  } as React.CSSProperties,
  splitBody: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
    height: 'calc(100% - 70px)',
  } as React.CSSProperties,
  menuPanel: {
    flex: 1.4,
    display: 'flex',
    flexDirection: 'column',
    padding: '1.5rem',
    borderRight: '1px solid var(--border-color)',
    overflowY: 'auto',
    gap: '1rem',
  } as React.CSSProperties,
  searchBar: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  searchIcon: {
    position: 'absolute',
    left: '1rem',
  } as React.CSSProperties,
  searchInput: {
    paddingLeft: '2.5rem',
    width: '100%',
  } as React.CSSProperties,
  categorySlider: {
    display: 'flex',
    gap: '0.5rem',
    overflowX: 'auto',
    paddingBottom: '0.25rem',
    flexShrink: 0,
  } as React.CSSProperties,
  categoryTab: {
    padding: '0.5rem 1rem',
    borderRadius: '8px',
    border: '1px solid var(--border-color)',
    fontWeight: 600,
    fontSize: '0.8rem',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
  dishesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '1rem',
    overflowY: 'auto',
    flex: 1,
    paddingRight: '0.25rem',
  } as React.CSSProperties,
  dishCard: {
    border: '1px solid var(--border-color)',
    borderRadius: '16px',
    overflow: 'hidden',
    textAlign: 'left',
    cursor: 'pointer',
    transition: 'all var(--transition-fast)',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  } as React.CSSProperties,
  dishImageColor: {
    height: '80px',
    width: '100%',
    position: 'relative',
    display: 'flex',
    alignItems: 'flex-end',
    padding: '0.5rem',
  } as React.CSSProperties,
  dishPriceBadge: {
    backgroundColor: 'rgba(9, 10, 15, 0.8)',
    backdropFilter: 'blur(4px)',
    color: 'white',
    padding: '0.25rem 0.5rem',
    borderRadius: '6px',
    fontSize: '0.8rem',
    fontWeight: 700,
  } as React.CSSProperties,
  dishInfo: {
    padding: '0.75rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    flex: 1,
  } as React.CSSProperties,
  dishName: {
    fontSize: '0.9rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: 0,
    lineHeight: '1.2',
  } as React.CSSProperties,
  dishDesc: {
    fontSize: '0.7rem',
    color: 'var(--text-secondary)',
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  } as React.CSSProperties,
  outOfStockOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(9,10,15,0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
  } as React.CSSProperties,
  outOfStockText: {
    backgroundColor: 'var(--color-error)',
    color: 'white',
    padding: '0.25rem 0.75rem',
    borderRadius: '6px',
    fontWeight: 800,
    fontSize: '0.75rem',
    letterSpacing: '0.05em',
  } as React.CSSProperties,
  ticketPanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: '1.5rem',
    backgroundColor: 'rgba(0,0,0,0.15)',
    overflowY: 'auto',
    gap: '1rem',
  } as React.CSSProperties,
  customerInputs: {
    display: 'flex',
    gap: '0.75rem',
  } as React.CSSProperties,
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  inputIcon: {
    position: 'absolute',
    left: '0.75rem',
    pointerEvents: 'none',
  } as React.CSSProperties,
  ticketTableContainer: {
    flex: 1,
    border: '1px solid var(--border-color)',
    borderRadius: '14px',
    backgroundColor: 'rgba(9, 10, 15, 0.3)',
    overflowY: 'auto',
    padding: '0.5rem',
  } as React.CSSProperties,
  ticketTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '0.85rem',
  } as React.CSSProperties,
  ticketTableRow: {
    borderBottom: '1px solid var(--border-color)',
  } as React.CSSProperties,
  itemQtyControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.25rem',
  } as React.CSSProperties,
  qtyBtn: {
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    border: '1px solid var(--border-color)',
    backgroundColor: 'transparent',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '0.75rem',
  } as React.CSSProperties,
  notesWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  } as React.CSSProperties,
  summaryBox: {
    padding: '1rem',
    borderRadius: '12px',
    backgroundColor: 'rgba(255,255,255,0.02)',
    border: '1px solid var(--border-color)',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  } as React.CSSProperties,
  summaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.85rem',
  } as React.CSSProperties,
  submitBtn: {
    height: '48px',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    fontWeight: 700,
    fontSize: '0.95rem',
  } as React.CSSProperties,
  emptyGrid: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-muted)',
    gap: '0.5rem',
    width: '100%',
    gridColumn: '1 / -1',
  } as React.CSSProperties,
};
