
export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
  } as React.CSSProperties,
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '1rem',
  } as React.CSSProperties,
  titleWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  } as React.CSSProperties,
  title: {
    fontSize: '2.25rem',
    marginBottom: '0.25rem',
  } as React.CSSProperties,
  subtitle: {
    color: 'var(--text-secondary)',
    fontSize: '0.95rem',
  } as React.CSSProperties,
  tabSwitcher: {
    display: 'flex',
    backgroundColor: 'rgba(0,0,0,0.2)',
    padding: '0.35rem',
    borderRadius: '14px',
    border: '1px solid var(--border-color)',
  } as React.CSSProperties,
  tabBtn: {
    border: 'none',
    padding: '0.5rem 1.25rem',
    borderRadius: '10px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '0.9rem',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
  kitchenLayout: {
    display: 'flex',
    gap: '2rem',
    height: 'calc(100vh - 180px)',
    overflow: 'hidden',
  } as React.CSSProperties,
  activeOrdersCol: {
    flex: 3,
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    overflowY: 'auto',
    paddingRight: '0.5rem',
  } as React.CSSProperties,
  sectionHeading: {
    fontSize: '1.1rem',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '0.25rem',
  } as React.CSSProperties,
  ordersGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '1.5rem',
  } as React.CSSProperties,
  orderCard: {
    padding: '1.25rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    borderRadius: '18px',
    backgroundColor: 'var(--bg-card)',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottom: '1px solid var(--border-color)',
    paddingBottom: '0.75rem',
  } as React.CSSProperties,
  cardTable: {
    fontSize: '1.3rem',
    fontWeight: 800,
    color: 'var(--text-primary)',
    display: 'block',
  } as React.CSSProperties,
  cardStatusLabel: {
    fontSize: '0.75rem',
    fontWeight: 700,
    letterSpacing: '0.05em',
  } as React.CSSProperties,
  cardTime: {
    fontSize: '0.75rem',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  cardClient: {
    fontSize: '0.85rem',
    backgroundColor: 'rgba(255,255,255,0.02)',
    padding: '0.4rem 0.75rem',
    borderRadius: '8px',
    color: 'var(--text-secondary)',
  } as React.CSSProperties,
  cardItemsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
    flex: 1,
    minHeight: '80px',
  } as React.CSSProperties,
  cardItemRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  } as React.CSSProperties,
  cardItemQty: {
    fontSize: '1.1rem',
    fontWeight: 800,
    color: 'var(--primary)',
    backgroundColor: 'rgba(249, 115, 22, 0.08)',
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
  } as React.CSSProperties,
  cardItemName: {
    fontSize: '1.05rem',
    fontWeight: 600,
  } as React.CSSProperties,
  cardNotes: {
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    borderLeft: '3px solid var(--color-error)',
    padding: '0.5rem 0.75rem',
    borderRadius: '6px',
    color: 'var(--text-primary)',
    fontSize: '0.85rem',
    strong: {
      fontSize: '0.8rem',
      color: 'var(--color-error)',
      display: 'block',
      marginBottom: '0.15rem',
    }
  } as React.CSSProperties,
  cardActions: {
    display: 'flex',
    gap: '0.5rem',
    marginTop: 'auto',
  } as React.CSSProperties,
  emptyCardContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '3rem 2rem',
    textAlign: 'center',
    height: '260px',
  } as React.CSSProperties,
  readyCol: {
    flex: 1,
    borderLeft: '1px solid var(--border-color)',
    paddingLeft: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  readyList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    overflowY: 'auto',
    flex: 1,
  } as React.CSSProperties,
  readyMiniCard: {
    padding: '0.75rem 1rem',
    backgroundColor: 'rgba(16, 185, 129, 0.02)',
    borderRadius: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  } as React.CSSProperties,
  miniCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as React.CSSProperties,
  miniCardItems: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.2rem',
    fontSize: '0.8rem',
    color: 'var(--text-secondary)',
  } as React.CSSProperties,
  miniCardItem: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  miniCardFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    borderTop: '1px dashed rgba(255,255,255,0.05)',
    paddingTop: '0.35rem',
  } as React.CSSProperties,
  inventoryPanel: {
    padding: '2rem',
    backgroundColor: 'var(--bg-card)',
  } as React.CSSProperties,
  inventoryHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid var(--border-color)',
    paddingBottom: '1.25rem',
    marginBottom: '1.5rem',
    flexWrap: 'wrap',
    gap: '1rem',
  } as React.CSSProperties,
  inventoryStats: {
    fontSize: '0.9rem',
    backgroundColor: 'rgba(0,0,0,0.2)',
    padding: '0.5rem 1rem',
    borderRadius: '10px',
    border: '1px solid var(--border-color)',
  } as React.CSSProperties,
  inventoryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gap: '1.25rem',
  } as React.CSSProperties,
  inventoryCard: {
    border: '1px solid var(--border-color)',
    borderRadius: '14px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
  inventoryCardColor: {
    height: '60px',
    width: '100%',
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  } as React.CSSProperties,
  invOutOfStockTag: {
    backgroundColor: 'var(--color-error)',
    color: 'white',
    fontSize: '0.75rem',
    fontWeight: 800,
    padding: '0.2rem 0.6rem',
    borderRadius: '6px',
  } as React.CSSProperties,
  inventoryCardInfo: {
    padding: '0.75rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.2rem',
  } as React.CSSProperties,
  inventoryCardName: {
    fontSize: '0.85rem',
    lineHeight: '1.2',
  } as React.CSSProperties,
  inventoryCardCat: {
    fontSize: '0.7rem',
    color: 'var(--text-muted)',
  } as React.CSSProperties,
  inventoryCardAction: {
    padding: '0.75rem',
    borderTop: '1px solid var(--border-color)',
    marginTop: 'auto',
  } as React.CSSProperties,
  toggleAvailBtn: {
    width: '100%',
    padding: '0.4rem',
    fontSize: '0.8rem',
    borderRadius: '8px',
  } as React.CSSProperties,
  detailsModal: {
    maxWidth: '460px',
    width: '100%',
    backgroundColor: 'var(--bg-sidebar)',
    padding: 0,
  } as React.CSSProperties,
  detailsModalHeader: {
    padding: '1.25rem 1.5rem',
    borderBottom: '1px solid var(--border-color)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.15)',
  } as React.CSSProperties,
};
