import React from 'react';

export const styles = {
  container: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    width: '100vw',
    backgroundColor: 'var(--bg-base)',
    backgroundImage: 'radial-gradient(circle at 50% 30%, rgba(249, 115, 22, 0.08) 0%, rgba(9, 10, 15, 0) 50%)',
    padding: '1.5rem',
  } as React.CSSProperties,
  card: {
    width: '100%',
    maxWidth: '460px',
    padding: '2.5rem 2rem',
    borderRadius: '24px',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'rgba(22, 26, 36, 0.9)',
    border: '1px solid var(--border-color)',
    boxShadow: 'var(--shadow-xl)',
    backdropFilter: 'blur(20px)',
  } as React.CSSProperties,
  logoContainer: {
    textAlign: 'center',
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  iconWrapper: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '70px',
    height: '70px',
    borderRadius: '20px',
    backgroundColor: 'rgba(249, 115, 22, 0.1)',
    border: '1px solid rgba(249, 115, 22, 0.2)',
    marginBottom: '1rem',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.05)',
  } as React.CSSProperties,
  title: {
    fontSize: '2rem',
    letterSpacing: '0.05em',
    marginBottom: '0.25rem',
    background: 'linear-gradient(to right, var(--text-primary), #fdba74)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    fontWeight: 800,
  } as React.CSSProperties,
  subtitle: {
    color: 'var(--text-secondary)',
    fontSize: '0.9rem',
  } as React.CSSProperties,
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  inputIcon: {
    position: 'absolute',
    left: '1rem',
    pointerEvents: 'none',
  } as React.CSSProperties,
  submitBtn: {
    marginTop: '0.5rem',
    width: '100%',
    height: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    fontWeight: 600,
  } as React.CSSProperties,
  errorAlert: {
    marginBottom: '1rem',
    padding: '0.75rem 1rem',
    fontSize: '0.85rem',
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    border: '1px solid var(--color-error-border)',
    borderRadius: '10px',
    color: 'var(--color-error)',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  captchaContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    marginTop: '0.5rem',
    marginBottom: '0.5rem',
  } as React.CSSProperties,
  captchaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  } as React.CSSProperties,
  captchaCanvas: {
    borderRadius: '10px',
    border: '1px solid var(--border-color)',
    backgroundColor: '#161a24',
    cursor: 'pointer',
  } as React.CSSProperties,
  refreshBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    border: '1px solid var(--border-color)',
    backgroundColor: 'rgba(255,255,255,0.03)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    transition: 'all var(--transition-fast)',
  } as React.CSSProperties,
  captchaInput: {
    paddingLeft: '1rem',
    height: '38px',
  } as React.CSSProperties,
};
